//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swashbuckle.DynamicLocalization.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Documentation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Documentation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swashbuckle.DynamicLocalization.Tests.TestData.Documentation", typeof(Documentation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the getter..
        /// </summary>
        internal static string Swashbuckle_DynamicLocalization_Tests_DocumentedController_Get_Description {
            get {
                return ResourceManager.GetString("Swashbuckle_DynamicLocalization_Tests_DocumentedController_Get_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id of the thing to get.
        /// </summary>
        internal static string Swashbuckle_DynamicLocalization_Tests_DocumentedController_Get_id {
            get {
                return ResourceManager.GetString("Swashbuckle_DynamicLocalization_Tests_DocumentedController_Get_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the getter..
        /// </summary>
        internal static string Swashbuckle_DynamicLocalization_Tests_DocumentedController_Get_Summary {
            get {
                return ResourceManager.GetString("Swashbuckle_DynamicLocalization_Tests_DocumentedController_Get_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test model..
        /// </summary>
        internal static string Swashbuckle_DynamicLocalization_Tests_DocumentedModel {
            get {
                return ResourceManager.GetString("Swashbuckle_DynamicLocalization_Tests_DocumentedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first property.
        /// </summary>
        internal static string Swashbuckle_DynamicLocalization_Tests_DocumentedModel_FirstProperty {
            get {
                return ResourceManager.GetString("Swashbuckle_DynamicLocalization_Tests_DocumentedModel_FirstProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second property.
        /// </summary>
        internal static string Swashbuckle_DynamicLocalization_Tests_DocumentedModel_SecondProperty {
            get {
                return ResourceManager.GetString("Swashbuckle_DynamicLocalization_Tests_DocumentedModel_SecondProperty", resourceCulture);
            }
        }
    }
}
