//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swashbuckle.DynamicLocalization.UsageExample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiDocumentation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiDocumentation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swashbuckle.DynamicLocalization.UsageExample.ApiDocumentation", typeof(ApiDocumentation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foo.
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_Foo {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_Foo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo&apos;s other thing.
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_Foo_OtherThing {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_Foo_OtherThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foo&apos;s thing.
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_Foo_Thing {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_Foo_Thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value..
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_FooController_Get_Description {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_FooController_Get_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id of the value to get..
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_FooController_Get_id {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_FooController_Get_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the value getter..
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_FooController_Get_Summary {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_FooController_Get_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts a value..
        /// </summary>
        public static string ResxDescriptionFilters_UsageExample_FooController_Post_Summary {
            get {
                return ResourceManager.GetString("ResxDescriptionFilters_UsageExample_FooController_Post_Summary", resourceCulture);
            }
        }
    }
}
